import {escape as esc,money,el} from './format.js';
import {invoiceCandidates} from './invoice-candidates.js';
import {differencePreview} from './invoice-difference.js';

function parseAmount(value){if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error('分配金额最多保留两位小数');const [whole,decimal='']=value.split('.');const result=Number(whole)*100+Number(decimal.padEnd(2,'0'));if(!Number.isSafeInteger(result)||result<=0)throw new Error('分配金额必须大于零且在有效范围内');return result;}
function option(row,selected,kind){const label=kind==='bank'?`${row.date} ${row.party} · 余额 ${money(row.remaining_cents)}`:`${row.date} ${row.party} · ${row.number} · 余额 ${money(row.remaining_cents)}`;return `<option value="${esc(row.id)}" ${row.id===selected?'selected':''}>${esc(label)}</option>`;}

export function allocationEditor(container,view,bank,onSave){
 const banks=view.bank.filter(b=>b.direction==='支出'&&!b.excluded_reason&&!b.hold_reasons.length&&b.remaining_cents>0);
 const invoices=view.invoices.filter(i=>!i.hold_reasons.length&&i.status!=='review'&&i.distributable_cents>0);
 const bm=new Map(banks.map(b=>[b.id,b])),im=new Map(invoices.map(i=>[i.id,i]));
 if(!bm.has(bank.id)){container.innerHTML='<p class="field-hint">当前流水已完成、不参与比对或存在异常待复核。可先撤回关联、调整分类，或到“冲突与复核”处理。</p>';return;}
 const rows=[{bank_id:bank.id,invoice_id:'',amount:''}];let prepared=null;
 container.innerHTML=`<h2 class="spaced">新增金额关联</h2><p class="muted">可增加多条付款与发票关联，先预览金额合计和余额，再确认保存。</p><div class="dialog-search"><input id="allocation-bank-search" placeholder="筛选付款：对方、日期或流水号" aria-label="筛选可选付款"><input id="allocation-invoice-search" placeholder="筛选发票：销方、日期或号码" aria-label="筛选可选发票"></div><label class="check-row"><input type="checkbox" id="allocation-other-companies"> 查看其他公司发票</label><p class="field-hint">默认仅显示每条付款对应交易对方的发票，支持已确认的名称映射。更换付款后发票列表同步更新。差额待确认或开票金额有误的发票暂停分配，可到“冲突与复核”处理。下拉框最多展示 100 个候选；输入名称、号码或日期可检索全部历史记录。</p><div id="allocation-rows"></div><button type="button" class="small-button" id="allocation-add">＋ 增加一条关联</button><label class="review-note" for="allocation-note">核对依据（必填）</label><textarea id="allocation-note" rows="2" placeholder="例如：按 8 月采购合同，9 月先开票 20,000 元"></textarea><div id="allocation-preview" class="allocation-preview" hidden></div><p id="allocation-error" class="form-error" role="alert"></p><div class="review-actions"><button class="small-button" id="allocation-preview-button">预览分配</button><button class="primary" id="allocation-save" hidden>确认保存这些关联</button></div>`;
 const rowBox=el('allocation-rows');
 function choices(all,selected,query,kind){const selectedRow=all.find(x=>x.id===selected);const matched=all.filter(x=>[x.party,x.date,x.number,x.reference,x.id].join(' ').includes(query));if(kind==='invoice')matched.sort((a,b)=>Number(bank.candidate_ids.includes(b.id))-Number(bank.candidate_ids.includes(a.id)));const list=matched.slice(0,100);if(selectedRow&&!list.includes(selectedRow))list.unshift(selectedRow);return '<option value="">请选择'+(kind==='bank'?'付款':'发票')+'</option>'+list.map(x=>option(x,selected,kind)).join('');}
 function invalidate(){prepared=null;el('allocation-preview').hidden=true;el('allocation-save').hidden=true;el('allocation-error').textContent='';}
 function render(){rowBox.innerHTML=rows.map((row,n)=>`<div class="allocation-row" data-index="${n}"><label>付款<select data-field="bank_id">${choices(banks,row.bank_id,el('allocation-bank-search').value,'bank')}</select><small>${row.bank_id?'付款剩余 '+money(bm.get(row.bank_id).remaining_cents)+' 元':''}</small></label><label>发票<select data-field="invoice_id">${choices(invoiceCandidates(view,bm.get(row.bank_id),el('allocation-other-companies').checked),row.invoice_id,el('allocation-invoice-search').value,'invoice')}</select><small>${row.invoice_id?'票面 '+money(im.get(row.invoice_id).amount_cents)+' · 可用 '+money(im.get(row.invoice_id).remaining_cents):(invoiceCandidates(view,bm.get(row.bank_id),el('allocation-other-companies').checked).length?'可跨月份选择':'没有符合条件的发票，可检查名称映射或勾选查看其他公司')}</small></label><label>本次分配（元）<input data-field="amount" type="text" inputmode="decimal" value="${esc(row.amount)}" placeholder="0.00"></label><button type="button" data-remove="${n}" aria-label="移除第 ${n+1} 条" class="icon-button">×</button></div>`).join('');}
 rowBox.addEventListener('change',e=>{const field=e.target.dataset.field;if(!field)return;const row=rows[Number(e.target.closest('[data-index]').dataset.index)];row[field]=e.target.value;if(field==='bank_id'&&!invoiceCandidates(view,bm.get(row.bank_id),el('allocation-other-companies').checked).some(i=>i.id===row.invoice_id)){row.invoice_id='';row.amount='';}if(field!=='amount'&&row.bank_id&&row.invoice_id)row.amount=(Math.min(bm.get(row.bank_id).remaining_cents,im.get(row.invoice_id).remaining_cents)/100).toFixed(2);invalidate();render();});
 rowBox.addEventListener('input',e=>{if(e.target.dataset.field==='amount'){rows[Number(e.target.closest('[data-index]').dataset.index)].amount=e.target.value;invalidate();}});
 rowBox.addEventListener('click',e=>{const target=e.target.closest('[data-remove]');if(target){rows.splice(Number(target.dataset.remove),1);invalidate();render();}});
 el('allocation-add').onclick=()=>{rows.push({bank_id:bank.id,invoice_id:'',amount:''});invalidate();render();};
 for(const id of ['allocation-bank-search','allocation-invoice-search'])el(id).oninput=render;
 el('allocation-other-companies').onchange=()=>{for(const row of rows){if(!invoiceCandidates(view,bm.get(row.bank_id),el('allocation-other-companies').checked).some(i=>i.id===row.invoice_id)){row.invoice_id='';row.amount='';}}invalidate();render();};
 el('allocation-note').oninput=invalidate;
 el('allocation-preview-button').onclick=()=>{try{
  if(!rows.length)throw new Error('请至少增加一条关联');const note=el('allocation-note').value.trim();if(!note)throw new Error('请填写核对依据');
  const bt=new Map(),it=new Map(),pairs=new Set();
  const allocations=rows.map(row=>{if(!bm.has(row.bank_id)||!im.has(row.invoice_id))throw new Error('请为每一条选择付款和发票');const pair=`${row.bank_id}/${row.invoice_id}`;if(pairs.has(pair))throw new Error('同一付款与发票在本次明细重复，请合为一条金额');pairs.add(pair);const amount_cents=parseAmount(row.amount);bt.set(row.bank_id,(bt.get(row.bank_id)||0)+amount_cents);it.set(row.invoice_id,(it.get(row.invoice_id)||0)+amount_cents);return {bank_id:row.bank_id,invoice_id:row.invoice_id,amount_cents};});
  for(const [id,n] of bt)if(n>bm.get(id).remaining_cents)throw new Error('付款本次分配合计超过剩余金额');for(const [id,n] of it)if(n>im.get(id).remaining_cents)throw new Error('发票本次分配合计超过可用余额');
  prepared={revision:view.revision,allocations,note};el('allocation-preview').innerHTML=`<strong>本次合计 ${money(allocations.reduce((s,a)=>s+a.amount_cents,0))} 元 · ${allocations.length} 条关联</strong>`+[...bt].map(([id,n])=>`<p>付款 ${esc(bm.get(id).date)} · ${esc(bm.get(id).party)}<br>本次 ${money(n)}，保存后累计 ${money(bm.get(id).allocated_cents+n)}，剩余 ${money(bm.get(id).remaining_cents-n)}</p>`).join('')+[...it].map(([id,n])=>`<p>发票 ${esc(im.get(id).number)} · 开票日期 ${esc(im.get(id).date)}<br>本次 ${money(n)}，保存后累计 ${money(im.get(id).allocated_cents+n)}，未分配 ${money(im.get(id).remaining_cents-n)}<br><span class="balance-warning">${esc(differencePreview(im.get(id),n,view))}</span></p>`).join('');el('allocation-preview').hidden=false;el('allocation-save').hidden=false;el('allocation-error').textContent='';
 }catch(error){invalidate();el('allocation-error').textContent=error.message;}};
 el('allocation-save').onclick=async()=>{if(!prepared)return;el('allocation-save').disabled=true;try{await onSave(prepared);}catch(error){el('allocation-error').textContent=error.message;el('allocation-save').disabled=false;}};
 render();
}
