import {escape as esc,money,el} from './format.js';

export function renderConflicts(state,onMutation){
 const view=state.result,pending=view.conflicts.filter(c=>c.state==='pending');
 const exceptions=view.invoices.filter(i=>i.red||i.invalid);
 el('conflict-count').textContent=pending.length+exceptions.filter(i=>!i.exception_review).length;
 el('conflict-list').innerHTML=pending.map(c=>{const existing=view[c.kind].filter(r=>c.record_ids.includes(r.id));return `<article class="conflict-card" data-conflict="${esc(c.id)}"><strong>${c.type==='version'?'同一编号出现不同版本':'缺少流水号，发现疑似重复'}</strong><p class="compact-text">新增来源：${esc(c.incoming.source)} · 第 ${c.incoming.row} 行</p><div class="table-scroll"><table class="dialog-table"><thead><tr><th>版本</th><th>日期</th><th>主体</th><th>金额</th><th>源状态 / 已分配</th><th>详情</th></tr></thead><tbody>${existing.map(r=>`<tr><td>账本原记录</td><td>${esc(r.date)}</td><td>${esc(r.party)}</td><td>${money(r.amount_cents)}</td><td>${esc(r.source_status||r.direction)} / ${money(r.allocated_cents)}</td><td><button class="text-button" data-${c.kind==='bank'?'bank':'invoice'}="${esc(r.id)}">详情</button></td></tr>`).join('')}<tr><td>新来源版本</td><td>${esc(c.incoming.date)}</td><td>${esc(c.incoming.party)}</td><td>${money(c.incoming.amount_cents)}</td><td>${esc(c.incoming.source_status||c.incoming.direction)}</td><td>待核对</td></tr></tbody></table></div><label>核对结果 <select class="resolution"><option value="keep">${c.type==='version'?'保留原记录，新版本仅保留为证据':'确认是重复记录，不新增金额'}</option><option value="${c.type==='version'?'accept':'new'}">${c.type==='version'?'接受新版本（先撤回原关联）':'确认是另一笔真实付款，新增入账'}</option></select></label><textarea class="resolution-note" rows="2" aria-label="冲突核对依据" placeholder="填写核对依据"></textarea><button class="primary resolve-button">保存本项核对</button><p class="form-error" role="alert"></p></article>`;}).join('')||'<div class="empty">没有未处理的来源冲突</div>';
 for(const card of el('conflict-list').querySelectorAll('[data-conflict]'))card.querySelector('.resolve-button').onclick=async()=>{try{await onMutation('/api/conflict',{revision:view.revision,conflict_id:card.dataset.conflict,action:card.querySelector('.resolution').value,note:card.querySelector('.resolution-note').value},false);}catch(error){card.querySelector('.form-error').textContent=error.message;}};
 el('exception-list').innerHTML=exceptions.map(i=>`<article class="conflict-card" data-exception="${esc(i.id)}"><strong>${esc(i.party)} · ${money(i.amount_cents)} 元</strong><p class="compact-text">${esc(i.number)} · ${esc(i.date)} · ${esc(i.red?'红字票':i.invalid)}</p><button class="text-button" data-invoice="${esc(i.id)}">查看关联与来源</button>${i.exception_review?`<p class="field-hint">已复核并保留异常票：${esc(i.exception_review.note)} · ${esc(i.exception_review.at)}</p>`:'<p class="field-hint">确认此异常票不需要冲抵当前付款后，可解除对同一销方其他记录的匹配阻止。此票仍保留异常状态，不用于核销；如涉及既有付款，请先撤回相应关联。</p><textarea class="exception-note" rows="2" aria-label="异常票复核依据" placeholder="说明与已有付款的关系及处理依据"></textarea><button class="small-button exception-button">已复核，保留异常票</button><p class="form-error" role="alert"></p>'}</article>`).join('')||'<p class="muted">无红字或异常票</p>';
 for(const card of el('exception-list').querySelectorAll('[data-exception]')){const button=card.querySelector('.exception-button');if(button)button.onclick=async()=>{try{await onMutation('/api/exception',{revision:view.revision,invoice_id:card.dataset.exception,note:card.querySelector('.exception-note').value},false);}catch(error){card.querySelector('.form-error').textContent=error.message;}};}
}
