import {renderRelations} from './allocation-relations.js';
import {escape as esc,money,el} from './format.js';
import {badge} from './ledger-view.js';
import {allocationEditor} from './allocation-editor.js';
import {differenceEditor} from './invoice-difference.js';
import {bankInvoiceNotices} from './bank-invoice-notices.js';

function sources(row){return `<details class="source-details"><summary>原始来源与长期编号（${row.sources.length} 次来源记录）</summary><p class="record-id">${esc(row.id)}</p>${row.sources.map(s=>`<p>${esc(s.file)} · ${esc(s.sheet)} · 第 ${s.row} 行<br><span class="record-id">SHA-256 ${esc(s.sha256)}<br>批次 ${esc(s.batch_id)}</span></p>`).join('')}</details>`;}
function open(title,body){el('detail-content').innerHTML=`<div class="dialog-heading"><h2>${title}</h2><button class="icon-button" data-close="detail-dialog" aria-label="关闭">×</button></div>${body}`;if(!el('detail-dialog').open)el('detail-dialog').showModal();}
export function showBank(state,id,onMutation){
 const view=state.result,b=view.bank.find(b=>b.id===id);if(!b)return;
 open('付款核对 · '+esc(b.date),`${badge(b,state.labels)}${bankInvoiceNotices(b)}<div class="detail-grid"><div class="detail-block"><label>交易对方</label><p>${esc(b.party||'银行费用')}</p><label>摘要</label><p>${esc(b.summary)}</p><label>账号 / 银行流水号</label><p class="monospace">${esc(b.account)}<br>${esc(b.reference||'缺少流水号')}</p></div><div class="detail-block"><label>原付款金额</label><p class="detail-amount">${money(b.amount_cents)}</p><label>累计有效核销 / 剩余金额</label><p>${money(b.allocated_cents)} / ${money(b.remaining_cents)} 元</p><label>当前依据</label><p>${esc(b.reason)}</p><label>手工备注</label><p class="bank-note-text">${esc(b.manual_note||'—')}</p><button class="text-button" data-bank-note="${esc(b.id)}">编辑备注</button></div></div>${sources(b)}<div id="detail-relations"></div><div id="allocation-editor"></div><details class="source-details"><summary>调整这笔付款的人工分类</summary><p>已有金额关联须先逐条撤回；摘要规则排除的流水可到“比对规则”调整。</p><textarea id="exclude-note" rows="2" placeholder="填写分类依据" aria-label="分类依据"></textarea><button class="small-button" id="exclude-save">${b.manual_exclusion?'撤回人工排除':'人工标记不参与比对'}</button><p class="form-error" id="exclude-error"></p></details>`);
 allocationEditor(el('allocation-editor'),view,b,p=>onMutation('/api/review',p));renderRelations(el('detail-relations'),view,view.allocations.filter(a=>a.bank_id===id),onMutation);
 el('exclude-save').onclick=async()=>{try{await onMutation('/api/exclusion',{revision:view.revision,bank_id:id,excluded:!b.manual_exclusion,note:el('exclude-note').value});}catch(error){el('exclude-error').textContent=error.message;}};
}
export function showInvoice(state,id,onMutation){const view=state.result,i=view.invoices.find(i=>i.id===id);if(!i)return;open('发票详情 · '+esc(i.date),`${badge(i,state.labels)}<div class="detail-grid"><div class="detail-block"><label>销售方</label><p>${esc(i.party)}</p><label>发票号码</label><p class="monospace">${esc(i.number)}</p><label>源状态 / 异常</label><p>${esc(i.source_status)} · ${esc(i.hold_reasons.join('；')||'无')}</p></div><div class="detail-block"><label>票面价税合计</label><p class="detail-amount">${money(i.amount_cents)}</p><label>已分配 / 未分配余额</label><p>${money(i.allocated_cents)} / ${money(i.remaining_cents)} 元</p><label>可继续分配</label><p>${money(i.distributable_cents)} 元</p></div></div>${sources(i)}<div id="detail-relations"></div><div id="invoice-difference-editor"></div><div id="action-area"></div>`);differenceEditor(el('invoice-difference-editor'),i,view,onMutation);renderRelations(el('detail-relations'),view,view.allocations.filter(a=>a.invoice_id===id),onMutation);}
export function showLegacy(result,labels){open('旧版记录 · 只读',`<p class="dialog-notice">此页显示旧批次结果。后续核对请返回累计账本；月份最新进度以“流水对账”为准。</p><p class="field-hint">${esc(result.bank_name)}<br>${esc(result.invoice_name)}</p><div class="table-scroll"><table><thead><tr><th>日期</th><th>对方</th><th>金额</th><th>旧版状态</th></tr></thead><tbody>${result.bank.map(b=>`<tr><td>${esc(b.date)}</td><td>${esc(b.party)}</td><td>${money(b.amount_cents)}</td><td>${badge(b,labels)}</td></tr>`).join('')}</tbody></table></div>`);}
