import {escape as esc,money,el} from './format.js';
import {badge} from './ledger-view.js';
import {allocationEditor} from './allocation-editor.js';

function sources(row){return `<details class="source-details"><summary>原始来源与长期编号（${row.sources.length} 次来源记录）</summary><p class="record-id">${esc(row.id)}</p>${row.sources.map(s=>`<p>${esc(s.file)} · ${esc(s.sheet)} · 第 ${s.row} 行<br><span class="record-id">SHA-256 ${esc(s.sha256)}<br>批次 ${esc(s.batch_id)}</span></p>`).join('')}</details>`;}
function relations(view,row,isBank){const allocations=view.allocations.filter(a=>a[isBank?'bank_id':'invoice_id']===row.id),bm=new Map(view.bank.map(b=>[b.id,b])),im=new Map(view.invoices.map(i=>[i.id,i]));return `<h2>金额关联明细</h2><div class="table-scroll"><table class="dialog-table"><thead><tr><th>付款日期 / 对方</th><th>开票日期 / 号码</th><th>本次核销</th><th>状态与依据</th><th>操作</th></tr></thead><tbody>${allocations.map(a=>`<tr><td>${esc(bm.get(a.bank_id).date)}<span class="subtext">${esc(bm.get(a.bank_id).party)}</span></td><td>${esc(im.get(a.invoice_id).date)}<span class="subtext">${esc(im.get(a.invoice_id).number)}</span></td><td class="number">${money(a.amount_cents)}</td><td>${a.state==='active'?'有效':'已撤回'}<span class="subtext">${esc(a.note)}${a.revoke_note?'<br>撤回：'+esc(a.revoke_note):''}</span></td><td>${a.state==='active'?`<button class="text-button" data-revoke="${esc(a.id)}">撤回</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty-row">尚未建立金额关联</td></tr>'}</tbody></table></div>`;}
function open(title,body){el('detail-content').innerHTML=`<div class="dialog-heading"><h2>${title}</h2><button class="icon-button" data-close="detail-dialog" aria-label="关闭">×</button></div>${body}`;if(!el('detail-dialog').open)el('detail-dialog').showModal();}
function bindRevoke(view,onMutation){for(const button of el('detail-content').querySelectorAll('[data-revoke]'))button.onclick=()=>{const id=button.dataset.revoke;el('action-area').innerHTML='<h2 class="spaced">撤回金额关联</h2><p class="field-hint">撤回保留证据和日志，并阻止此付款与发票自动重新关联；之后仍可人工确认。</p><textarea id="revoke-note" rows="2" placeholder="填写撤回依据" aria-label="撤回依据"></textarea><button class="primary spaced" id="revoke-save">确认撤回本条关联</button><p id="action-error" class="form-error" role="alert"></p>';el('revoke-save').onclick=async()=>{try{await onMutation('/api/undo',{revision:view.revision,allocation_id:id,note:el('revoke-note').value});}catch(error){el('action-error').textContent=error.message;}};el('action-area').scrollIntoView({block:'nearest'});};}
export function showBank(state,id,onMutation){
 const view=state.result,b=view.bank.find(b=>b.id===id);if(!b)return;
 open('付款核对 · '+esc(b.date),`${badge(b,state.labels)}<div class="detail-grid"><div class="detail-block"><label>交易对方</label><p>${esc(b.party||'银行费用')}</p><label>摘要</label><p>${esc(b.summary)}</p><label>账号 / 银行流水号</label><p class="monospace">${esc(b.account)}<br>${esc(b.reference||'缺少流水号')}</p></div><div class="detail-block"><label>原付款金额</label><p class="detail-amount">${money(b.amount_cents)}</p><label>累计有效核销 / 剩余金额</label><p>${money(b.allocated_cents)} / ${money(b.remaining_cents)} 元</p><label>当前依据</label><p>${esc(b.reason)}</p></div></div>${sources(b)}${relations(view,b,true)}<div id="action-area"></div><div id="allocation-editor"></div><details class="source-details"><summary>调整这笔付款的人工分类</summary><p>已有金额关联须先逐条撤回；摘要规则排除的流水可到“比对规则”调整。</p><textarea id="exclude-note" rows="2" placeholder="填写分类依据" aria-label="分类依据"></textarea><button class="small-button" id="exclude-save">${b.manual_exclusion?'撤回人工排除':'人工标记不参与比对'}</button><p class="form-error" id="exclude-error"></p></details>`);
 allocationEditor(el('allocation-editor'),view,b,p=>onMutation('/api/review',p));bindRevoke(view,onMutation);
 el('exclude-save').onclick=async()=>{try{await onMutation('/api/exclusion',{revision:view.revision,bank_id:id,excluded:!b.manual_exclusion,note:el('exclude-note').value});}catch(error){el('exclude-error').textContent=error.message;}};
}
export function showInvoice(state,id,onMutation){const view=state.result,i=view.invoices.find(i=>i.id===id);if(!i)return;open('发票详情 · '+esc(i.date),`${badge(i,state.labels)}<div class="detail-grid"><div class="detail-block"><label>销售方</label><p>${esc(i.party)}</p><label>发票号码</label><p class="monospace">${esc(i.number)}</p><label>源状态 / 异常</label><p>${esc(i.source_status)} · ${esc(i.hold_reasons.join('；')||'无')}</p></div><div class="detail-block"><label>票面价税合计</label><p class="detail-amount">${money(i.amount_cents)}</p><label>已分配 / 可用余额</label><p>${money(i.allocated_cents)} / ${money(i.remaining_cents)} 元</p></div></div>${sources(i)}${relations(view,i,false)}<div id="action-area"></div>`);bindRevoke(view,onMutation);}
export function showLegacy(result,labels){open('旧版记录 · 只读',`<p class="dialog-notice">此页显示旧批次结果。后续核对请返回累计账本；月份最新进度以“流水对账”为准。</p><p class="field-hint">${esc(result.bank_name)}<br>${esc(result.invoice_name)}</p><div class="table-scroll"><table><thead><tr><th>日期</th><th>对方</th><th>金额</th><th>旧版状态</th></tr></thead><tbody>${result.bank.map(b=>`<tr><td>${esc(b.date)}</td><td>${esc(b.party)}</td><td>${money(b.amount_cents)}</td><td>${badge(b,labels)}</td></tr>`).join('')}</tbody></table></div>`);}
